### ISSUE TITLE
BUG: Sometimes the (HTML-JavaFX) Panel doesnt scale to position on startup

### ISSUE THREAD

**Issue by sojournercntl** [eProtectioneers/ProjectPanacea#8]
Like playing poker. Sometimes you win sometimes you don't. The GUI Scales when the program has been started and closed sometimes. 
**Working:**
![eprotectioneers-panacea](https://cloud.githubusercontent.com/assets/14313625/26020113/3167d91a-377b-11e7-889c-683d400c4fe6.PNG)
**Bug:**
![bug](https://cloud.githubusercontent.com/assets/14313625/26020140/65df830a-377b-11e7-92fe-e197b00ed83b.PNG)

**Comment by Simsen3142** [comment]
Bug can be fixed with an Override of the paintComponent-Method of MainPanel, where the jfxPanel gets resized

**Comment by sojournercntl** [comment]
Got it thanks 👍 
![ppcaworkspace](https://cloud.githubusercontent.com/assets/14313625/26024755/d64443b2-37d8-11e7-94c7-269bea0cc49f.PNG)
